// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_evasions = "CgkIuNGY0MkMEAIQAw"; // <GPGSID>
        public const string event_koizumi_pick = "CgkIuNGY0MkMEAIQCg"; // <GPGSID>
        public const string event_yasumi_pick = "CgkIuNGY0MkMEAIQGw"; // <GPGSID>
        public const string achievement_kuyou_win = "CgkIuNGY0MkMEAIQKw"; // <GPGSID>
        public const string event_asakura_pick = "CgkIuNGY0MkMEAIQBg"; // <GPGSID>
        public const string event_kimidori_kill = "CgkIuNGY0MkMEAIQCQ"; // <GPGSID>
        public const string achievement_mikuru_win = "CgkIuNGY0MkMEAIQJw"; // <GPGSID>
        public const string event_total_users_connected = "CgkIuNGY0MkMEAIQDg"; // <GPGSID>
        public const string event_kimidori_pick = "CgkIuNGY0MkMEAIQCw"; // <GPGSID>
        public const string event_sasaki_pick = "CgkIuNGY0MkMEAIQFw"; // <GPGSID>
        public const string achievement_koizumi_win = "CgkIuNGY0MkMEAIQKQ"; // <GPGSID>
        public const string event_tournament_played = "CgkIuNGY0MkMEAIQHw"; // <GPGSID>
        public const string event_tsuruya_kill = "CgkIuNGY0MkMEAIQGg"; // <GPGSID>
        public const string achievement_asakura_win = "CgkIuNGY0MkMEAIQKA"; // <GPGSID>
        public const string event_koizumi_kill = "CgkIuNGY0MkMEAIQDA"; // <GPGSID>
        public const string event_mikuru_kill = "CgkIuNGY0MkMEAIQFA"; // <GPGSID>
        public const string event_sasaki_kill = "CgkIuNGY0MkMEAIQGA"; // <GPGSID>
        public const string event_asakura_kill = "CgkIuNGY0MkMEAIQBw"; // <GPGSID>
        public const string achievement_kyouko_win = "CgkIuNGY0MkMEAIQMg"; // <GPGSID>
        public const string achievement_buff_object_activated = "CgkIuNGY0MkMEAIQMA"; // <GPGSID>
        public const string event_kuyou_kill = "CgkIuNGY0MkMEAIQEA"; // <GPGSID>
        public const string event_haruhi_picks = "CgkIuNGY0MkMEAIQBQ"; // <GPGSID>
        public const string event_pvp_played = "CgkIuNGY0MkMEAIQHQ"; // <GPGSID>
        public const string event_kuyou_pick = "CgkIuNGY0MkMEAIQDw"; // <GPGSID>
        public const string event_team_played = "CgkIuNGY0MkMEAIQIA"; // <GPGSID>
        public const string leaderboard_highest_score = "CgkIuNGY0MkMEAIQAg"; // <GPGSID>
        public const string event_mikuru_pick = "CgkIuNGY0MkMEAIQEw"; // <GPGSID>
        public const string achievement_total_wins = "CgkIuNGY0MkMEAIQIg"; // <GPGSID>
        public const string achievement_haruhi_win = "CgkIuNGY0MkMEAIQJg"; // <GPGSID>
        public const string event_tsuruya_pick = "CgkIuNGY0MkMEAIQGQ"; // <GPGSID>
        public const string achievement_sasaki_win = "CgkIuNGY0MkMEAIQLQ"; // <GPGSID>
        public const string event_kyouko_kill = "CgkIuNGY0MkMEAIQEQ"; // <GPGSID>
        public const string leaderboard_kills = "CgkIuNGY0MkMEAIQBA"; // <GPGSID>
        public const string achievement_total_kills = "CgkIuNGY0MkMEAIQIw"; // <GPGSID>
        public const string event_pve_played = "CgkIuNGY0MkMEAIQHg"; // <GPGSID>
        public const string event_yasumi_kill = "CgkIuNGY0MkMEAIQHA"; // <GPGSID>
        public const string achievement_tsuruya_win = "CgkIuNGY0MkMEAIQLg"; // <GPGSID>
        public const string event_total_games_played = "CgkIuNGY0MkMEAIQDQ"; // <GPGSID>
        public const string achievement_kimidori_win = "CgkIuNGY0MkMEAIQKg"; // <GPGSID>
        public const string event_nagato_kill = "CgkIuNGY0MkMEAIQFg"; // <GPGSID>
        public const string leaderboard_pve_time = "CgkIuNGY0MkMEAIQIQ"; // <GPGSID>
        public const string leaderboard_victories = "CgkIuNGY0MkMEAIQAQ"; // <GPGSID>
        public const string achievement_yasumi_win = "CgkIuNGY0MkMEAIQLw"; // <GPGSID>
        public const string event_haruhi_kill = "CgkIuNGY0MkMEAIQCA"; // <GPGSID>
        public const string achievement_nagato_win = "CgkIuNGY0MkMEAIQJQ"; // <GPGSID>
        public const string event_kyouko_pick = "CgkIuNGY0MkMEAIQEg"; // <GPGSID>
        public const string achievement_empty = "CgkIuNGY0MkMEAIQLA"; // <GPGSID>
        public const string achievement_total_evades = "CgkIuNGY0MkMEAIQJA"; // <GPGSID>
        public const string event_nagato_pick = "CgkIuNGY0MkMEAIQFQ"; // <GPGSID>

}

